### ISSUE TITLE
サーバー側の最適化問題

### ISSUE THREAD

**Issue by sakastudio** [moorestech/moorestech#194]
雑な検証
ベルトコンベア50個で0.25ms

![image](https://github.com/moorestech/moorestech/assets/55620461/eb43c9f1-d20b-4962-9fd5-5fcaa722124b)

サーバー側の更新頻度は100msとしているけど、おそらくベルコン1万個までは耐えられそう
ゲーム的にもそれくらいの工場は求められないと思うが、不安は残る数

https://www.factorio.com/blog/post/fff-176

こういうのを参考に最適化していくのがよさそう

**Comment by KurisuJuha** [comment]
高速化したい部分だけECSを使用するとかすると良さそう
「ベルトコンベアの実体をECSにおいて、処理の最後にECSにあるデータをmonobehaviourに反映」みたいな

**Comment by KurisuJuha** [comment]
ECSにすると、mod開発者側も既存の処理の改変やデータの改変がしやすくなるので

**Comment by sakastudio** [comment]
たしかに、一部分を切り出してブロックの実態はECSへのリンクとして機能させるのはアリですね～

**Comment by sakastudio** [comment]
後で取り組むので今はいったんclose
