### ISSUE TITLE
[VS] チャートの作成、チャートに必要なシステムの作成

### ISSUE THREAD

**Issue by sakastudio** [moorestech/moorestech#210]
# Tokudaやること

- [ ] とりあえずできるところまで遊ぶ

# sakastudioやること

- [ ] 歯車関連のシステム開発

**Comment by RyotaTokuda** [comment]
miroのチャートをムアステのエディタを使って作成するところ、Unityで遊べるようにするところはやりますー！

**Comment by sakastudio** [comment]
これ系は以後notion側で管理
