### ISSUE TITLE
[VS] 3x3のマイクラ風クラフトをやめてワンクリッククラフトにする

### ISSUE THREAD

**Issue by sakastudio** [moorestech/moorestech#219]
- [ ] UI変更、リファクタ
- [ ] 足りないものを視覚的にわかるように

# 背景

いまの3x3のクラフト画面は明確な目的があって実装されたものではない（マイクラを忠実に再現するという目的以外の目的がない）
ワンクリッククラフトでできることに違いはない、ただ手間が増えているだけ

マイクラのNEI付きクラフト画面も自動配置機能があって、ワンクリッククラフトとあまり変わらない

# 実装方法

今はテストとしてワンクリッククラフトを作る

とりあえず今のクラフト画面は残すとして、右側のアイテム一覧をクリックすることでクラフトする
クラフトできるものは白に、できないものはグレーに

**Comment by KurisuJuha** [comment]
factorioのように制作自体に時間はかかるように変更するんですか？それとも今まで通り時間はかからない感じですか？

**Comment by sakastudio** [comment]
とりあえず時間はかからないですが、Factorioのように原料まで辿って自動クラフトみたいなのは無しかな〜とちょっと思ってます

**Comment by KurisuJuha** [comment]
ちなみに自動クラフトが無しの理由ってあります？

**Comment by sakastudio** [comment]
- 作るのが面倒
- 手元クラフトで解決しちゃうのは自動化をしないモチベになりがち
- クラフトできないアイテム（機械加工でしか手に入らないアイテム）を多めにしてくて、自動クラフトの意味が薄いから

みたいなイメージです

**Comment by KurisuJuha** [comment]
なるほどです

**Comment by sakastudio** [comment]
現在サーバー側実装中

**Comment by sakastudio** [comment]
# UIメモ

https://www.gameuidatabase.com/gameData.php?id=472
https://www.gameuidatabase.com/gameData.php?id=293
https://www.gameuidatabase.com/gameData.php?id=291
https://www.gameuidatabase.com/gameData.php?id=1696
https://www.gameuidatabase.com/gameData.php?id=38
https://www.gameuidatabase.com/gameData.php?id=1488
https://www.gameuidatabase.com/gameData.php?id=1695

**Comment by sakastudio** [comment]
# UI参考

モンハンワールド
![image](https://github.com/moorestech/moorestech/assets/55620461/6f4d1d87-7193-4c78-a031-8c0864feb877)

ポータルナイツ
![image](https://github.com/moorestech/moorestech/assets/55620461/c356fab5-5efc-40ec-8746-ac4aa41e0be3)

switch版マイクラ
![image](https://github.com/moorestech/moorestech/assets/55620461/259c90ff-66d1-4b58-ab19-6f1ead7c9e93)

ドラクエビルダー
![image](https://github.com/moorestech/moorestech/assets/55620461/2cc576ec-4112-4baf-8988-bba32b47ebc6)

**Comment by sakastudio** [comment]
サーバー側はできたのでこれはクローズ
