### ISSUE TITLE
3. RPMとトルクをvalue objectにする

### ISSUE THREAD

**Issue by sakastudio** [moorestech/moorestech#374]
unit generetorつかう

ご存じかもしれませんが一応
UnitGeneretorのオプションを使えば、比較、演算を可能にできます
https://github.com/moorestech/moorestech/pull/380/files#diff-616cb2e1cbc138fd16806e2cb3afbc15662fe2181f379927f7aa1b459dcd7bddR5

**Comment by KurisuJuha** [comment]
https://github.com/moorestech/moorestech/pull/380/files#diff-616cb2e1cbc138fd16806e2cb3afbc15662fe2181f379927f7aa1b459dcd7bddR5

からImplicitOperatorを削除
